services:
  db:
    container_name: evoter-mvc
    image: postgres
    environment:
      POSTGRES_USER: esther
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5235:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: